### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by wifi75** [AuxXxilium/arpl#39]
Hello' I have apl loader 1.0.2, a few days ago I tried to update to version 1.0.5, it was the latest available at that time, after the update, I did the building on reboot, nothing worked anymore, or better DSM could not find the disk.

why?

**Comment by AuxXxilium** [comment]
Don't know. Diagnostic with no more Information is not possible.

**Comment by wifi75** [comment]
do you have to rebuild the boot after the update?

**Comment by AuxXxilium** [comment]
yes, you have to

**Comment by wifi75** [comment]
I don't understand what happens then because after the rebuilding DSM loses the configuration, it doesn't see any disk anymore.
It may happen that during this update and rebuilding the missing drivers are no longer selected?

**Comment by AuxXxilium** [comment]
please use latest version

**Comment by AuxXxilium** [comment]
Please do not use DS1621+ if you use an Raid/SCSI/SAS Controller. Use DS3622xs+

**Comment by wifi75** [comment]
i don't have any scsi raid, i have sata on proxmox

**Comment by AuxXxilium** [comment]
Please send me the output of the "edit user config" in aio. first screen is enough

**Comment by wifi75** [comment]
![image](https://user-images.githubusercontent.com/31816231/202164681-b9b81372-5241-422a-b7ee-05b7b07fe0d4.png)

**Comment by AuxXxilium** [comment]
Have you made a new config after update?

**Comment by wifi75** [comment]
yes new config from new file arpl.img 1.0.15

**Comment by AuxXxilium** [comment]
the first is: you dont need 9p as an addon. its buildin as a module.

**Comment by wifi75** [comment]
ok i removed it

**Comment by AuxXxilium** [comment]
rebuild and try please

**Comment by wifi75** [comment]
removed 9p built, but can't find disc.
This has always been my problem with proxmox all along.
the sata disk 1 is not empty there is already the DSM inside.
![image](https://user-images.githubusercontent.com/31816231/202167032-ceb78a45-9ee8-4dca-bf71-326adc593991.png)

**Comment by AuxXxilium** [comment]
You have an SCSI Controller in your VM. Can you remove it?

**Comment by wifi75** [comment]
proxmox doesn't allow you to remove the scsi controller.

**Comment by wifi75** [comment]
maybe I can try to change nas model?

**Comment by AuxXxilium** [comment]
so your disks use scsi

**Comment by wifi75** [comment]
proxmox, auto add scsi controller, but i have only sata disks inside pc.

**Comment by AuxXxilium** [comment]
yes you can, but proxmox will handle the disks like scsi

**Comment by wifi75** [comment]
every time you create a new VM in proxmox, it always adds scsi controller, it doesn't allow you to remove the scsi controller...now i changed the model of nas i chose DS3622XS+, in fact now the disk sees it....
![image](https://user-images.githubusercontent.com/31816231/202170472-9fe9d8c8-a8e0-4af5-a1f7-f5590f63bb84.png)

so with proxmox better to choose this model?
Yet when I installed everything from the beginning I had chosen the ds1621+ model, but the sata disk was empty...

**Comment by AuxXxilium** [comment]
yes, ds3622xs+ is better for everything

**Comment by wifi75** [comment]
Ok thank you for all !!!
